import bcrypt from 'bcryptjs';

export const initialCategories = [
  {
    id: 'cat-mens',
    name: "Men's Atelier",
    slug: 'mens',
    tagline: 'Tailored silhouettes, refined outerwear, and modern minimalist essentials.',
    image: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=1000&q=85',
    itemCount: 24,
    featured: true,
    displayOrder: 1,
  },
  {
    id: 'cat-womens',
    name: "Women's Collection",
    slug: 'womens',
    tagline: 'Fluid tailoring, sculptured knitwear, and effortless contemporary dressing.',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1000&q=85',
    itemCount: 32,
    featured: true,
    displayOrder: 2,
  },
  {
    id: 'cat-footwear',
    name: 'Footwear & Boots',
    slug: 'footwear',
    tagline: 'Hand-lasted leather boots, architectural loafers, and technical runners.',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1000&q=85',
    itemCount: 18,
    featured: true,
    displayOrder: 3,
  },
  {
    id: 'cat-bags',
    name: 'Artisanal Leather Bags',
    slug: 'bags',
    tagline: 'Structured totes, crossbodies, and weekender duffles engineered to last.',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1000&q=85',
    itemCount: 14,
    featured: true,
    displayOrder: 4,
  },
  {
    id: 'cat-watches',
    name: 'Timepieces & Horology',
    slug: 'watches',
    tagline: 'Clean sapphire crystal dials, automatic movements, and brushed steel cases.',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1000&q=85',
    itemCount: 12,
    featured: true,
    displayOrder: 5,
  },
  {
    id: 'cat-accessories',
    name: 'Accessories & Eyewear',
    slug: 'accessories',
    tagline: 'Japanese acetate frames, silk scarves, and forged brass jewelry accents.',
    image: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&w=1000&q=85',
    itemCount: 20,
    featured: false,
    displayOrder: 6,
  },
  {
    id: 'cat-living',
    name: 'Modern Living & Objects',
    slug: 'living',
    tagline: 'Tactile ceramics, cast bronze incense burners, and organic linen textiles.',
    image: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1000&q=85',
    itemCount: 16,
    featured: false,
    displayOrder: 7,
  },
];

export const initialProducts = [
  {
    id: 'prod-01',
    name: 'Soren Oversized Wool Trench Coat',
    slug: 'soren-oversized-wool-trench-coat',
    brand: 'AURA Atelier',
    category: "Men's Atelier",
    categorySlug: 'mens',
    price: 8900,
    originalPrice: 10500,
    rating: 4.9,
    reviewCount: 42,
    stock: 12,
    sku: 'AUR-M-TRC-001',
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isFlashSale: false,
    badge: 'Bestseller',
    images: [
      'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1000&q=85',
    ],
    colors: [
      { name: 'Camel Tan', hex: '#C29B7F' },
      { name: 'Obsidian Noir', hex: '#1C1C1E' },
      { name: 'Heather Charcoal', hex: '#4A4A4F' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'A monument to modern minimalist tailoring. Cut from dense 480gsm double-faced Australian merino wool with exaggerated storm flaps, horn buttons, and an unstructured shoulder drape.',
    overview: 'The Soren trench reimagines timeless military outerwear through a contemporary Scandinavian lens. Designed for fluid movement, it layers effortlessly over fine knitwear or tailored suiting.',
    specifications: {
      Material: '100% Australian Merino Wool (480gsm)',
      Lining: '100% Bemberg Cupro',
      Buttons: 'Engraved Natural Buffalo Horn',
      Origin: 'Crafted in Porto, Portugal',
      Care: 'Specialist Dry Clean Only',
    },
    status: 'published',
  },
  {
    id: 'prod-02',
    name: 'Elysian Sculpted Cashmere Turtleneck',
    slug: 'elysian-sculpted-cashmere-turtleneck',
    brand: 'AURA Atelier',
    category: "Women's Collection",
    categorySlug: 'womens',
    price: 5200,
    originalPrice: 6200,
    rating: 4.95,
    reviewCount: 38,
    stock: 18,
    sku: 'AUR-W-CSH-002',
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isFlashSale: false,
    badge: 'Editor Pick',
    images: [
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1000&q=85',
    ],
    colors: [
      { name: 'Alabaster Chalk', hex: '#F0EEE9' },
      { name: 'Warm Taupe', hex: '#9E8B7D' },
      { name: 'Midnight Navy', hex: '#1B2432' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'An ethereal staple knit from Grade-A Mongolian cashmere with a ribbed high collar, elongated cuffs, and a gently curved hem.',
    overview: 'Spun to a featherlight 12-gauge tension, the Elysian turtleneck offers supreme thermal regulation without bulk. An essential layering canvas for transitional weather.',
    specifications: {
      Material: '100% Mongolian Cashmere (2-ply 12-gauge)',
      Gauge: 'Fine 12gg rib-knit collar and cuffs',
      Origin: 'Knitted in Biella, Italy',
      Care: 'Hand wash cold or gentle dry clean',
    },
    status: 'published',
  },
  {
    id: 'prod-03',
    name: 'Kanso Minimalist Leather Chelsea Boot',
    slug: 'kanso-minimalist-leather-chelsea-boot',
    brand: 'AURA Footwear',
    category: 'Footwear & Boots',
    categorySlug: 'footwear',
    price: 7400,
    originalPrice: 8500,
    rating: 4.85,
    reviewCount: 29,
    stock: 8,
    sku: 'AUR-F-CHL-003',
    isFeatured: true,
    isBestseller: false,
    isNewArrival: true,
    isFlashSale: false,
    badge: 'New Arrival',
    images: [
      'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=1000&q=85',
    ],
    colors: [
      { name: 'Matte Onyx', hex: '#1E1E1E' },
      { name: 'Waxed Cigar', hex: '#583D2A' },
    ],
    sizes: ['40', '41', '42', '43', '44', '45'],
    description: 'Handcrafted Goodyear-welted Chelsea boots shaped on our proprietary chisel toe last. Seamless whole-cut Italian box calf leather with reinforced elastic side gussets.',
    overview: 'The Kanso boot pairs architectural proportion with rugged durability. Features a custom Vibram lugged half-sole for traction across wet city pavements.',
    specifications: {
      Upper: 'Full-grain Italian Calfskin',
      Construction: 'Goodyear Welted with storm welt',
      Sole: 'Vibram Commando rubber half-sole',
      Origin: 'Artisanal workshop in Marche, Italy',
    },
    status: 'published',
  },
  {
    id: 'prod-04',
    name: 'Vessel Structured Leather Weekender',
    slug: 'vessel-structured-leather-weekender',
    brand: 'AURA Leathercraft',
    category: 'Artisanal Leather Bags',
    categorySlug: 'bags',
    price: 11200,
    originalPrice: 13000,
    rating: 4.92,
    reviewCount: 19,
    stock: 6,
    sku: 'AUR-B-WKD-004',
    isFeatured: true,
    isBestseller: false,
    isNewArrival: false,
    isFlashSale: true,
    badge: 'Limited Run',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1000&q=85',
    ],
    colors: [
      { name: 'Vegetable Espresso', hex: '#3B2317' },
      { name: 'Cognac Saddle', hex: '#8B4513' },
    ],
    sizes: ['45L Carry-On'],
    description: 'Engineered for seamless travel. Vegetable-tanned Tuscan leather develops a rich, golden patina over years of journeying. Meets international airline carry-on dimensions.',
    overview: 'Features dedicated padded compartment for 16-inch laptops, ventilated shoe garage, and solid hand-turned brass hardware.',
    specifications: {
      Leather: '3.2mm Tuscan Vegetable-Tanned Cowhide',
      Hardware: 'Solid brushed Japanese brass',
      Zippers: 'YKK Excella polished metal zippers',
      Volume: '45 Litres',
    },
    status: 'published',
  },
];

export const initialCoupons = [
  {
    id: 'coup-1',
    code: 'AURA10',
    type: 'percentage',
    value: 10,
    minSpend: 2000,
    expiryDate: '2026-12-31T23:59:59Z',
    usageLimit: 500,
    timesUsed: 42,
    active: true,
  },
  {
    id: 'coup-2',
    code: 'FIRSTORDER',
    type: 'percentage',
    value: 15,
    minSpend: 3000,
    expiryDate: '2026-11-30T23:59:59Z',
    usageLimit: 1000,
    timesUsed: 128,
    active: true,
  },
  {
    id: 'coup-3',
    code: 'LUXE500',
    type: 'fixed',
    value: 500,
    minSpend: 5000,
    expiryDate: '2026-12-15T23:59:59Z',
    usageLimit: 200,
    timesUsed: 89,
    active: true,
  },
];

export const initialReviews = [
  {
    id: 'rev-01',
    productId: 'prod-01',
    author: 'Tahmid Chowdhury',
    rating: 5,
    date: '2026-09-18',
    title: 'Flawless wool drape and silhouette',
    comment: 'The weight of the 480gsm wool is extraordinary. It falls with such clean architectural lines. Worth every taka.',
    verified: true,
    status: 'Approved',
  },
  {
    id: 'rev-02',
    productId: 'prod-01',
    author: 'Farhana Hossain',
    rating: 5,
    date: '2026-09-22',
    title: 'Exceeded all expectations',
    comment: 'Purchased for my partner for winter travels. The natural horn buttons and interior finishing are on par with Paris fashion houses.',
    verified: true,
    status: 'Approved',
  },
  {
    id: 'rev-03',
    productId: 'prod-02',
    author: 'Nadia Rahman',
    rating: 5,
    date: '2026-09-25',
    title: 'Incredible cashmere softness',
    comment: 'Light as a cloud yet retains warmth effortlessly. The collar stays upright without suffocating. Highly recommend.',
    verified: true,
    status: 'Approved',
  },
];

export const defaultCmsContent = {
  hero: {
    badge: 'Autumn / Winter 2026 Collection',
    headline: 'Designed with Intention. Crafted to Endure.',
    supportingCopy: 'Architectural tailoring, Australian merino wool, and Italian vegetable-tanned leather essentials crafted for the modern wardrobe.',
    primaryCtaText: 'Explore New Arrivals',
    primaryCtaLink: '/shop?filter=new',
    secondaryCtaText: 'The Season Edit',
    secondaryCtaLink: '/about',
    heroImage: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=1200&q=85',
  },
  announcement: {
    enabled: true,
    text: 'Complimentary white-glove delivery on all orders over ৳3,000 across Bangladesh.',
    linkText: 'Shop New Arrivals',
    linkUrl: '/shop',
  },
  promotionalBanner: {
    title: 'THE MODERN ATELIER EDIT',
    subtitle: 'Limited Production Runs',
    description: 'Each piece is hand-numbered and cut in limited volumes to eliminate textile waste and preserve exclusivity.',
    ctaText: 'Discover Collection',
    ctaLink: '/category/mens',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=85',
  },
};

export const defaultStoreSettings = {
  storeName: 'AURA Studio',
  storeTagline: 'Modern Architectural Fashion & Objects',
  supportEmail: 'concierge@aurastudio.com',
  supportPhone: '+880 1712 345 678',
  addressLine1: 'House 14, Road 11, Block D',
  city: 'Banani, Dhaka 1213',
  country: 'Bangladesh',
  currency: 'BDT (৳)',
  insideDhakaShipping: 60,
  outsideDhakaShipping: 120,
  freeShippingThreshold: 3000,
  taxRatePercent: 0,
  enableGuestCheckout: true,
  enableCod: true,
  enableBkash: true,
  maintenanceMode: false,
};

export const initialOrders = [
  {
    id: 'AUR-2026-9481',
    orderNumber: 'AUR-2026-9481',
    customerName: 'Tariq Rahman',
    customerPhone: '+880 1712 345678',
    customerEmail: 'tariq.rahman@example.com',
    customerAddress: 'House 42, Road 11, Block D, Banani',
    customerCity: 'Dhaka',
    customerPostalCode: '1213',
    subtotal: 10700,
    discountAmount: 1070,
    deliveryFee: 0,
    totalAmount: 9630,
    total: 9630,
    shippingFee: 0,
    couponCode: 'AURA10',
    paymentMethod: 'bKash / Nagad',
    paymentStatus: 'Paid',
    orderStatus: 'Delivered',
    createdAt: '2026-09-20T14:32:00Z',
    deliveredAt: '2026-09-22T17:15:00Z',
    customer: {
      fullName: 'Tariq Rahman',
      phone: '+880 1712 345678',
      email: 'tariq.rahman@example.com',
      address: 'House 42, Road 11, Block D, Banani',
      city: 'Dhaka',
      postalCode: '1213',
    },
    shippingAddress: {
      street: 'House 42, Road 11, Block D, Banani',
      city: 'Dhaka',
      postalCode: '1213',
    },
    items: [
      {
        id: 'prod-01',
        productId: 'prod-01',
        name: 'Soren Overized Wool Trench Coat',
        productNameSnapshot: 'Soren Overized Wool Trench Coat',
        skuSnapshot: 'AUR-M-TRN-001',
        price: 8900,
        unitPrice: 8900,
        quantity: 1,
        color: 'Camel Tan',
        size: 'L',
        image: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=400&q=80',
        lineTotal: 8900,
      },
    ],
    pricing: {
      subtotal: 10700,
      shippingFee: 0,
      discount: 1070,
      total: 9630,
      couponCode: 'AURA10',
    },
  },
  {
    id: 'AUR-2026-9482',
    orderNumber: 'AUR-2026-9482',
    customerName: 'Samira Chowdhury',
    customerPhone: '+880 1819 876543',
    customerEmail: 'samira.chowdhury@example.com',
    customerAddress: 'Apt 5B, Navana Tower, Gulshan-2',
    customerCity: 'Dhaka',
    customerPostalCode: '1212',
    subtotal: 6400,
    discountAmount: 0,
    deliveryFee: 0,
    totalAmount: 6400,
    total: 6400,
    shippingFee: 0,
    couponCode: null,
    paymentMethod: 'Credit / Debit Card',
    paymentStatus: 'Paid',
    orderStatus: 'Shipped',
    createdAt: '2026-09-24T11:20:00Z',
    customer: {
      fullName: 'Samira Chowdhury',
      phone: '+880 1819 876543',
      email: 'samira.chowdhury@example.com',
      address: 'Apt 5B, Navana Tower, Gulshan-2',
      city: 'Dhaka',
      postalCode: '1212',
    },
    shippingAddress: {
      street: 'Apt 5B, Navana Tower, Gulshan-2',
      city: 'Dhaka',
      postalCode: '1212',
    },
    items: [
      {
        id: 'prod-02',
        productId: 'prod-02',
        name: 'Elysian Sculpted Cashmere Turtleneck',
        productNameSnapshot: 'Elysian Sculpted Cashmere Turtleneck',
        skuSnapshot: 'AUR-W-CSH-002',
        price: 5200,
        unitPrice: 5200,
        quantity: 1,
        color: 'Alabaster Chalk',
        size: 'S',
        image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=1000&q=85',
        lineTotal: 5200,
      },
    ],
    pricing: {
      subtotal: 5200,
      shippingFee: 0,
      discount: 0,
      total: 5200,
      couponCode: null,
    },
  },
];

export const initialCustomers = [
  {
    id: 'cust-01',
    fullName: 'Tariq Rahman',
    email: 'tariq.rahman@example.com',
    phone: '+880 1712 345678',
    address: 'House 42, Road 11, Block D, Banani',
    city: 'Dhaka',
    orderCount: 1,
    totalSpent: 9630,
    lastOrderDate: '2026-09-20T14:32:00Z',
  },
  {
    id: 'cust-02',
    fullName: 'Samira Chowdhury',
    email: 'samira.chowdhury@example.com',
    phone: '+880 1819 876543',
    address: 'Apt 5B, Navana Tower, Gulshan-2',
    city: 'Dhaka',
    orderCount: 1,
    totalSpent: 6400,
    lastOrderDate: '2026-09-24T11:20:00Z',
  },
];

export const createSuperAdminData = async () => {
  const salt = await bcrypt.genSalt(10);
  const passwordHash = await bcrypt.hash('admin123', salt);
  return {
    id: 'usr_admin_01',
    name: 'Mahir Arman',
    email: 'admin@aurastudio.com',
    password_hash: passwordHash,
    role: 'super_admin',
    is_active: true,
  };
};
